# Generated by Django 2.0.3 on 2018-03-13 19:32

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=500)),
                ('post_slug', models.SlugField(max_length=500)),
                ('post_body', models.TextField()),
                ('post_publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to=blog.models.content_file_name)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
