# Generated by Django 2.0.3 on 2018-03-13 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=500)),
                ('post_slug', models.SlugField(max_length=500)),
                ('post_body', models.TextField()),
                ('post_publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
